name: C/C++ CI

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master", "ci" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: make
    - name: make check
      run: make check CTEST_OUTPUT_ON_FAILURE=TRUE
